### ISSUE TITLE
Download problem on DeviantArt

### ISSUE THREAD

**Issue by JarieSuicune** [catgirlfighter/nekopaw#305]
Every time I've tried to download a gallery from DA, everything tagged as "Explicit" gets skipped over, with the preview save location showing the .%ext% at the end, apparently not finding the extension?

**Comment by catgirlfighter** [comment]
Before quite a recent update you wasn't able to access Mature pictures without authentication. It means you have to log in to see it in a current version of deviantart's script.
But right now I got an issue with authentication on deviantart (whenever libraries I try, DA denies me with handshake failure). Right now I'm looking for salvation, also I'll update a script to autoconfirm your age.
