### ISSUE TITLE
How to add website on graber 2?

### ISSUE THREAD

**Issue by RagaSonic** [catgirlfighter/nekopaw#306]
All is in tilte.

(ex: https://www.atfbooru.ninja )

**Comment by RagaSonic** [comment]
Help?

**Comment by catgirlfighter** [comment]
I don't really made or want to make a guideline or something, and looks like that booru doesn't use a basic engine (like gelbooru or danbooru or something), or it was heavily modified. Doesn't look hard, tho, so I'll make a script for you.

**Comment by RagaSonic** [comment]
thank you :)

**Comment by catgirlfighter** [comment]
Simplest version of it, without authorization and pools.
[atfbooru.ninja.cfg.txt](https://github.com/catgirlfighter/nekopaw/files/21836/atfbooru.ninja.cfg.txt)

Rename .cfg.txt to .cfg and drop it in "resources" folder.

**Comment by RagaSonic** [comment]
Thanks you for helping :)

**Comment by HanatakeYurii** [comment]
Thanks for this, was also searching for it.

Does not ATFbooru would replace the entry for AllTheFallen (ATF) since it's replace it's gallery (the link goes to it)?

**Comment by RagaSonic** [comment]
Since the last update the program gets to download than the 5 first page.
