### ISSUE TITLE
Error trying to get list on Pururin

### ISSUE THREAD

**Issue by MintGreenIceCream** [catgirlfighter/nekopaw#307]
I get this error whenever I try to get the list down on Pururin.

20:07:32 pururin.com: @thread.execute(): http://pururin.com/search?q=f&p=0: HTTP/1.1 503 Service Temporarily Unavailable

This only started happening recently.

**Comment by JarieSuicune** [comment]
That would be due to the site itself. Check the sources before suspecting the program.

**Comment by MintGreenIceCream** [comment]
It probably has something to do with the site checking browsers before allowing them into the site, anyway to work around it with nekopaw?

**Comment by catgirlfighter** [comment]
ATM I always get a "The initial connection between CloudFlare's network and the origin web server timed out. As a result, the web page can not be displayed." error (pururin was blocked from my region not so long ago, so I tried with Tokyo and Amsterdam proxy). Can't really verify anything. I'll try to do it in a week.

**Comment by catgirlfighter** [comment]
Can't access it directly, and my proxy gives me CloudFlare's network error. Is it even still working?

**Comment by catgirlfighter** [comment]
After all the time I still can't access pururin, neither directly nor via proxy.
