### ISSUE TITLE
Access Denied problem

### ISSUE THREAD

**Issue by Applepiee** [catgirlfighter/nekopaw#308]
Hello!

I really appreciate the time that you took to create this tool, even after all these years you're still updating, thanks for that!

I wanted to use your tool but encountered several problems..

When I used the updater it downloads 2.1.0.135a and for some reason the menu's are having encoding problems. => http://prntscr.com/97u3ar

So I decided to download the latest version from github here, which is 2.1.0.141a

But when I try to grab images I get an access denied error http://prntscr.com/97u3j0

I had the same error when I tried to update  2.1.0.135a => http://prntscr.com/97u3o4

Any idea what can cause this? I tried changing my region to USA and I tried to run as Administrator

Windows 10 - X64

Thanks in advance!

**Comment by anyway01** [comment]
Hello there!

I also want to say thanks for you creating this friggin' useful tool and for still updating it.

I have to second the issue Applepiee mentioned:
["I had the same error when I tried to update 2.1.0.135a => http://prntscr.com/97u3o4"]

I can't get the program updated anymore, the page names in the selection list are not visible and each time I try to update there appears an error 403.

Update issue:
http://o04.imgup.net/0222a3911.png
http://u25.imgup.net/0222bb6d.png
http://f62.imgup.net/0111e624.png

Page list issue:
http://p78.imgup.net/03332864.png

Windows 7, X64

Best greetings

**Comment by catgirlfighter** [comment]
Should work now, but you have to redownload it.
For picture downloading s mandatory to set a fake, browser like agent string. Didn't notice I didn't use it for updater :)

**Comment by anyway01** [comment]
Hello, catgirlfighter!

Another issue came up... Now I can't open the program at all anymore.

The folder I put the downloaded new .exe files into just won't respond anymore after the mouse cursor gets stuck in the "Please wait" mode after I tried to open the program. T_T

**Comment by catgirlfighter** [comment]
That's weird. Works fine for me (win7x32). Don't even know, how I can help you. Maybe it corrupted while downloaded? Try to redownload it, or check your security settings, probably something hanging it trying to verify it safety?

**Comment by catgirlfighter** [comment]
Tested on Win10x64, too. Works fine as well.

**Comment by anyway01** [comment]
That's really strange...

I have checked the background processes and found this: http://u48.imgup.net/05558d3c.png

The program seems to try get run but the window won't open... It seems to get stuck at a certain point?

Win7, x64

Another strange thing is that the old version 2.1.0.135ALPHA still opens without any problems.

**Comment by catgirlfighter** [comment]
If it doesn't launch, it get stuck right at beginning :)
Old one may open because it wasn't "new application from internet", and doesn't require verifying. Can you check your Avast antivirus if it interfere in any way?

Also try to launch NPUpdater in a clear folder, without other files (looks like madness, but what if graber2.exe somehow affect it?).

At last, try "unlock" in file properties ("This file came from another computer..." thing in properties).

**Comment by anyway01** [comment]
Okay, dear catgirlfighter, we just found the cause: Avast antivirus is the culprit not wanting to let neither the Graber2 nor the NPUpdater get opened/updated.

**Comment by catgirlfighter** [comment]
No problem. It's usual behavior for antivirus. I would recommend to setup antivirus in a way it doesn't block Nekopaw (or figure out, why it doesn't allow it), because it's kind of insecure to disable antivirus every time :)

**Comment by anyway01** [comment]
Okay, only one last thing to mention: You can just whitelist the file path of the Graber folder. Works perfectly.

Another time I want to thank you.
https://shiheemwallis.files.wordpress.com/2014/02/snore.jpg

Best greetings from Germany

anyway01

**Comment by Applepiee** [comment]
Thanks for fixing the updater.
But I still can't seem to login and download from rule34.paheal.net
http://prntscr.com/9a57j9

Does it work for you?

**Comment by catgirlfighter** [comment]
No, it doesn't work for me for 1.5 years now, it was blocked from our country. Testing something like this needs special circumstances and preparations, that's why most of the time I'm just tool lazy to deal with it.

**Comment by Applepiee** [comment]
I see. Too bad. Thanks for the info though!

**Comment by RagaSonic** [comment]
I use eset nod32. I unactivate I tried to update but not work.
I'm on W10 64bit. (http://prntscr.com/97u3o4)
Is this may be related to bug update download?
https://gyazo.com/5b8491a698dd1c68e561aa9efad16ae4

**Comment by catgirlfighter** [comment]
@RagaSonic,
You need to redownload an updater. It can't fix itself from your PC.

**Comment by RagaSonic** [comment]
Work for me thanks. :)
