### ISSUE TITLE
Preventing bad folder names with a period at the end.

### ISSUE THREAD

**Issue by JarieSuicune** [catgirlfighter/nekopaw#312]
If possible, it would be good to have some protection against the program generating a folder that ends in a period. This can be caused by downloading galleries that the name ends in a period, as well as by user mistake.

Removing these can be quite troublesome to do, though I finally found a simple way: using 7Zip's file manager, first rename the folder then delete/whatever the folder.

**Comment by catgirlfighter** [comment]
Have to work now.
