### ISSUE TITLE
Source failing to download?

### ISSUE THREAD

**Issue by JarieSuicune** [catgirlfighter/nekopaw#313]
Trying to download from exhentai, neither url or tag search is working. It finds the album itself just fine, but then it fails to download anything.
I haven't changed any settings since the last successful download (just a few days ago), so not sure why it stopped working.
The directory it shows as trying to make ends with the final generated folder name/0
ie: c://directory/albumname/0

**Comment by catgirlfighter** [comment]
So, seems now it's all right?

**Comment by JarieSuicune** [comment]
Yes, thank you.
I'm rather confused why that setting didn't cause problems before, but since I don't need it on anyways, I figure it's better now.
