### ISSUE TITLE
exhentai & g.e-hentai.org small change in address -> naming problems.

### ISSUE THREAD

**Issue by Zzzyyzzyxx** [catgirlfighter/nekopaw#315]
Hello,

Apparently, Exhentai (and so, certainly g.e-hentai.org) just had a small change in their code/address link.

The link to the 'Fullsized' images (higher than 1200*x) when available as changed just today.
OLD style: 
http://37.48.81.80/ehg/image.php?f=081e042a0b9af66ac29caccb37a4649b1d0eaf98-855029-1600-1200-jpg&t=403820-e846f5fdca63884e61260237fad0fb9bc6f4bbd2&n=TOP1600.jpg&dl=1
NEW style: 
http://37.48.81.80/im/081e042a0b9af66ac29caccb37a4649b1d0eaf98-855029-1600-1200-jpg/403839-99a0b18fc6e012b3ed59aa5c16df1e51b9c2a566/TOP1600.jpg?dl=1

Certainly because of this change, Nekopaw is now unable to obtain the correct 'original_name' and the '$ext$' for those Fullsized images. (no problems with small size images).
From now on, all fullsized images are named '1' with no $ext$.

Thanks for your great software!

**Comment by catgirlfighter** [comment]
I don't think it "changed", they added one more. For now I already transforming two of them. I'll figure it out.

**Comment by catgirlfighter** [comment]
Made a new little update. Should do.
Basically, all that changed is they added ?dl=1 in the end in second variant.

**Comment by JarieSuicune** [comment]
I still can't download anything from those resources. I put the Tag to search, or the address of the gallery, and it find it ok, but when I start the download, it does something, then just marks it with "Skip" and then repeats through the rest of the list the same way.

**Comment by catgirlfighter** [comment]
I guess, you have to give me your resource's config and a tag you use. I can download things just fine.

**Comment by catgirlfighter** [comment]
Config includes your file's name format.

**Comment by JarieSuicune** [comment]
Saving format:
E:\Pictures\Artist Collections\[ehentai]\$tag$\%album%\$fname$

Example tag:
artist:kkuem$

**Comment by catgirlfighter** [comment]
Works well for me.
http://imgur.com/GT8Eb8g

Can you give me the reset of resource's config? Screenshot of all checkboxes, for example.

**Comment by JarieSuicune** [comment]
Hopefully this shows what you are looking for.

![artist](https://cloud.githubusercontent.com/assets/689847/12679302/a5572836-c660-11e5-94a5-ebda6f63747f.jpg)

if the attachment didn't work, then here's a link to the image on Dropbox:
https://www.dropbox.com/s/yw4cf6s9otwtng9/Artist.jpg

**Comment by catgirlfighter** [comment]
I guess I figured it out.
If you hover over "Download Archives" checkbox  you will see "(spends Credits)". You can't download it freely. And "download archives" makes grabber download not pictures, but archives. Grabber doesn't throw an error when can't find an URL for an archive, that's why it skips it. I guess I need to make it a bit more clear when you out of credits to download something.

**Comment by JarieSuicune** [comment]
That fixed it! Weird, I've not touched those settings in long time, but it never had any problems until now.
Oh, does the program now pause/stop when you hit the download limit (when they replace the image with a GIF informing you of that limit)? Or is that a setting I haven't noticed?

**Comment by catgirlfighter** [comment]
That was a thing for a long time :)
