### ISSUE TITLE
Download problem on ATF

### ISSUE THREAD

**Issue by RagaSonic** [catgirlfighter/nekopaw#317]
Since the last update the program gets to download than the 5 first page max.

**Comment by catgirlfighter** [comment]
Not quite. It's just when there is too many pictures for a search result ( > 99 pages, I think) it doesn't show number of a last page (i.e. highest is 5th).

**Comment by catgirlfighter** [comment]
Made changes around atf. Replaces ld one with atfbooru, and fixed 5 pages download.

**Comment by RagaSonic** [comment]
:) thanks work again.
