### ISSUE TITLE
Can't download pics on nhentai

### ISSUE THREAD

**Issue by Ruriko** [catgirlfighter/nekopaw#319]
So I added a couple of urls and let it finish getting the list. Once the list is finished I pressed the start download pictures but nothing happens. There are no errors either. This is my folder path settings: C:\Users\Administrator\Downloads\doujin\1-4\%album_id%_%album:.200s%\$fname$
![nhentai](https://cloud.githubusercontent.com/assets/5670857/13319007/56fc1c0e-dc0a-11e5-9edb-72b83af86e5f.jpg)

**Comment by catgirlfighter** [comment]
Works fine for me, both by keywords and album's urls. Show me your resource's config and tag string (urls?) that doesn't work for you.

**Comment by Ruriko** [comment]
nvm I found the problem I didn't select the correct source
