### ISSUE TITLE
Can't close tab with really long name

### ISSUE THREAD

**Issue by Pernat1y** [catgirlfighter/nekopaw#320]
Possible solutions that i see:
Move close button to the left from caption
Limit lengh of showed tab caption
Add close button to drop-down menu

![image](https://cloud.githubusercontent.com/assets/1016979/13374637/33f8e266-dd93-11e5-81c4-58340817405b.png)

**Comment by catgirlfighter** [comment]
Made a fixed length of 40 symbols for tab's title.
