### ISSUE TITLE
Hentai-Foundry login failed

### ISSUE THREAD

**Issue by Wiggelz** [catgirlfighter/nekopaw#321]
Each time I try to log in to Hentai-Foundry it just gives the error 'login is failed'
I tried multiple accounts and made a new account just to try with. I can log in fine from my browser, just not the program.

**Comment by catgirlfighter** [comment]
Possibly they changed something in logging in. I'll see.

**Comment by catgirlfighter** [comment]
Didn't encounter any issues. Sorry. Try to redownload, I guess?
Delete "settings.ini" for full download, or delete string "*\hentai-foundry.ini" from file "settings.ini" for just one file.
