### ISSUE TITLE
nhentai 503 error

### ISSUE THREAD

**Issue by Ruriko** [catgirlfighter/nekopaw#322]
version 2.1.0148a gives this error and I usually have to retry downloading a couple times to fix that error
```
20:00:39 nhentai.net: @thread.execute(): http://nhentai.net/g/80146/1/: HTTP/1.1 503 Service Temporarily Unavailable
20:00:39 nhentai.net: @thread.execute(): http://nhentai.net/g/77183/1/: HTTP/1.1 503 Service Temporarily Unavailable
20:00:39 nhentai.net: @thread.execute(): http://nhentai.net/g/80157/1/: HTTP/1.1 503 Service Temporarily Unavailable
20:00:39 nhentai.net: @thread.execute(): http://nhentai.net/g/85941/1/: HTTP/1.1 503 Service Temporarily Unavailable
```

but on the older version 2.1.01.46a doesn't give that error so I didn't need to retry downloading

**Comment by catgirlfighter** [comment]
All 400-500 HTTP errors happen only due to server issues. Maybe their servers are busy, or they added something to slow down downloading if you download too much or too fast. Try to change your threads settings.
