### ISSUE TITLE
ExHentai login failed 

### ISSUE THREAD

**Issue by JacobDNN** [catgirlfighter/nekopaw#325]
After their maintenance today, nekopaw can't login into exhentai.

**Comment by catgirlfighter** [comment]
It figures they changed something. I hope nothing too big.

**Comment by catgirlfighter** [comment]
Didn't encounter any issues. Logged in without problems with my old account.

**Comment by JacobDNN** [comment]
Yep, sorry, it works today. Just had to wait a little bit.
