### ISSUE TITLE
Feature request - Image Tags

### ISSUE THREAD

**Issue by JarieSuicune** [catgirlfighter/nekopaw#326]
Is it possible to have the image tags saved to the downloaded image files? It may be something rarely used, but it could be a useful option for some people.
(I ask because I noticed that while looking through an image's properties that it included a "tags" section)

If this is already a feature, how do I enable it?

**Comment by catgirlfighter** [comment]
Yes, it's a feature. I believe I made it working in all resources that support a tag collection. When you setup a list of resources, look for an option "write metadata to JPEG files" in "general". Only JPEG files support tags initially, and adding metadata messing up MD5 of a picture, so it has its flaws.

**Comment by JarieSuicune** [comment]
Ah, I finally found it!

Also, does it add all tags listed for each given image, or just the ones used in the search, if any?

**Comment by catgirlfighter** [comment]
Everything resource has for a current picture. It doesn't add anything from search parameters ("search tag" including). If resource doesn't provide tagging, it doesn't add metadata.

**Comment by naruhina2016** [comment]
hey nekopaw your software is awesome but i have a problem how can i add tags to the pictures i want to download i only get them in numbers and letters please tell me...:(
