### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by naruhina2016** [catgirlfighter/nekopaw#328]
hello nekopaw,

while downloading pictures with tags it also gives me some error 
most of them didn't even download at all so can i fix this please tell me...:(

**Comment by catgirlfighter** [comment]
Hey.
Nekopaw can download pictures from very different resources, and they have different rules of searching. You have to know, which resources compatible witch each other. So it's natural that you get errors if you just add random resources and trying to search with the same keywords.

**Comment by naruhina2016** [comment]
but now i have another problem $tags$ thats what gives an error while downloading so how can fix it?

**Comment by catgirlfighter** [comment]
I need screenshots, logs, config (tag and settings) and exact names of resources you have problems with to be able to answer.

**Comment by naruhina2016** [comment]
http://s1078.photobucket.com/user/naruhina2016/media/Untitled2_zpsbakio7mo.png.html?filters[user]=144876174&filters[recent]=1&sort=1&o=0

http://s1078.photobucket.com/user/naruhina2016/media/Untitled1_zpsl8as8qvv.png.html?filters[user]=144876174&filters[recent]=1&sort=1&o=1

here are the screenshots you requested and the source is chan.sankakucomplex but i didn't know what you wanted from the settings so can u please tell me what u exactly need?

**Comment by naruhina2016** [comment]
?

**Comment by JarieSuicune** [comment]
If you don't mind, I think I see the problem: You are downloading the file with the tags in the filename... and the generated filenames generated are FAR too long. (The file path+name can't exceed 255 digits, from ROOT to the end of the extension.) Basically, change your save preferences, there is no program-end fix. You should be able to set the program to save tags into the image file data (viewable in Image Properties) if you really want the tags.
Unless I'm wrong. Still, basically a bad idea to download with tags from a booru-type site, due to the sheer length it can become. (Be GLAD it's not saving those, because then they become difficult to do anything with; your system can't read/move/delete/edit overly-long filenames natively).

**Comment by catgirlfighter** [comment]
Sorry for a long wait. I fell ill, and basically spaced out from things.
That's exactly what Suicune said. That's a bit weird, because I made a change in app that should keep names below 255 symbols range, but it didn't trigger in your case.

**Comment by naruhina2016** [comment]
but still where can i find image properties and what do you mean with save preferences do you mean that i should save the image somewhere else other than the regular root file?

**Comment by catgirlfighter** [comment]
With different name. remove $tags$ from name format. Name of resulting file is too long.

**Comment by naruhina2016** [comment]
but then it will not be tagged...:(

**Comment by catgirlfighter** [comment]
Yep. You can save tags in EXIF (metadata) in JPEG files, but it not supported in the rest of extensions. Also you can save names + md5 + tags in CSV after files are downloaded. But you can't keep tags in filenames, file system doesn't support long names.

**Comment by naruhina2016** [comment]
aha ic but where can i find exif and csv?

**Comment by catgirlfighter** [comment]
EXIF - when you make a list General -> Save to JPEG metadata
csv - when your list is done, press save list (diskette icon), chose csv.

**Comment by naruhina2016** [comment]
and then it will be tagged once i start downloading pictures?

**Comment by catgirlfighter** [comment]
Why not just try it?

**Comment by naruhina2016** [comment]
so after saving those list as csv i have to download the pictures and then they will be tagged bcause i did save the list but when i want to load it it gives me an error

**Comment by catgirlfighter** [comment]
When you csv list in tells you that is saves only downloaded pictures. It means you need to download first.

What kind of error you get now?

**Comment by naruhina2016** [comment]
so first download pictures and then load the list?

**Comment by catgirlfighter** [comment]
Save, not load.

**Comment by catgirlfighter** [comment]
You still remember that you CAN'T use long filenames, and saving tags in metadata and csv files doesn't fix it?

**Comment by naruhina2016** [comment]
how do i save tags in metadata? and what do i do with the list that i saved after it downloaded the lists?

**Comment by catgirlfighter** [comment]
>how do i save tags in metadata?
>EXIF (metadata) - when you make a list General -> Save to JPEG metadata

>and what do i do with the list that i saved after it downloaded the lists?
Whatever you need tags for.

**Comment by naruhina2016** [comment]
well i did save the list but do i ahve to check or uncheck metadata? and where on metadata do i add tags?

**Comment by catgirlfighter** [comment]
When you check an option, it means "yes, please do", and when you leave it unchecked, it means "no, please don't do". It means when you check an option "write metadata" app will write metadata, because you asked it to do so. And if you leave it unchecked, app will not save metadata, because app gonna think you asked it not to.
You don't add tags in metadata. They added automatically..

**Comment by naruhina2016** [comment]
so i have to remove tags from saving path or what?

**Comment by catgirlfighter** [comment]
Yes, you should. Because they make your filename too long.

**Comment by naruhina2016** [comment]
i meant the saving path above metadata

**Comment by catgirlfighter** [comment]
In General you set all the settings that apply to all resources in the list (except when you chose not to inherit that settings when you setting up certain resources).

**Comment by naruhina2016** [comment]
aha ic well ill try thanks anyways
