### ISSUE TITLE
All download attmepts return Access is Denied error

### ISSUE THREAD

**Issue by chromzepher** [catgirlfighter/nekopaw#330]
Hey, thanks for the hard work you've been putting in. Every time I try to download anything through the app since I updated I just get the following error  `Cannot create file <path>. Access is denied`. Not sure what might be causing this and I don't really know where else to look for assistance. Thanks in advance.

**Comment by catgirlfighter** [comment]
To be fair, it possible only if you don't have an access to that directory. User, that you launch an app with, doesn't have rights to write in that directory. Possibly it's antivirus or "what to do with programs from internet" policy. You should check your security measures.

**Comment by chromzepher** [comment]
AV is disabled and I've attempted to run the program as administrator. Where would I find find the options for "what to do with programs from the internet" on Win10x64?

**Comment by catgirlfighter** [comment]
Did you try to just change a path? To something that's not on the same drive as your OS.
I don't know, where to look for Win10 options (because I didn't run into issues like that before), but you can unmark an exe file as "file from internet (another computer)" in file's properties. At last, in w7.

**Comment by chromzepher** [comment]
So I changed the file path, which still returned the same error, then changed it back to the original path and now it's working fine? Go figure. Thanks for you help. Also I couldn't find where to modify the origin of an .exe in win10. Either way it's working now. Thanks for your help and keep up the good work!

**Comment by catgirlfighter** [comment]
Heh. You welcome, I guess :)
