### ISSUE TITLE
Furaffinity Login Changes

### ISSUE THREAD

**Issue by lolirider** [catgirlfighter/nekopaw#333]
![untitled-1](https://cloud.githubusercontent.com/assets/19730213/18834145/90ea8730-83b1-11e6-9c2e-648c39183bd7.jpg)

They Added Captcha Verification For Added security
Can't login with grabber

**Comment by Kelleidorn** [comment]
Добрый вечер, catgirlfighter.
Я Вам уже писал на почту, но напишу и здесь. Возможно ли в принципе организовать обход рекапчи средствами конфигов или подгружать её при каждом логине в программе?

**Comment by catgirlfighter** [comment]
Yeah, gotta do something about it during next week.

Неа, функционала работать с капчей нет. Постараюсь реализовать что-нибудь в течении след. недели.

**Comment by Kelleidorn** [comment]
Спасибо за ответ.
catgirlfighter, написал на почту (gmail). Может что-нибудь придумаем.

**Comment by Kelleidorn** [comment]
Добрый вечер, catgirlfighter.
Вы получили моё письмо? Как обстоят дела с добавлением функционала, есть какие-нибудь идеи? Если есть идеи, но нет времени, пните в нужную сторону.
PS. Кстати, как насчёт добавления InkBunny.net?

**Comment by Kelleidorn** [comment]
Добрый вечер, catgirlfighter.
Как продвигаются дела с Furaffinity? И как насчёт добавления InkBunny.net?

**Comment by catgirlfighter** [comment]
Added captcha. I hope it works.

**Comment by Kelleidorn** [comment]
Работает! Огромное спасибо!
