### ISSUE TITLE
Deviantart downloads going into loops

### ISSUE THREAD

**Issue by anyway01** [catgirlfighter/nekopaw#334]
Hello, catgirlfighter, it's me again.

I found an issue which is kinda irritating even though it's not blocking out the downloads I wish to do:

When I want to download an artist's gallery on deviantart, there are always certain image links which appear in the generated download list over and over again. The image duplicates won't even be skipped due to the actual image already having been downloaded but downloaded again and put an (xy number) at the end of the file name.

Is there a way to prevent the download list from generating a whole lot of link duplicates?

Here are some images about this issue:
https://picload.org/image/rgpddllw/01.png
https://picload.org/image/rgpddlcr/02.png
https://picload.org/image/rgpddcad/03.png
https://picload.org/image/rgpddcao/04.png

Best greetings

anyway01

**Comment by catgirlfighter** [comment]
It's a bit late, but... I didn't get anything like that. I tried "by user's gallery" and "by user's gallery (name in tags), with and w/o "group by folders", and issue didn't occur. I need more data about how you setup your download. I guess you can't log in like anyone else, right?
![sample6](https://cloud.githubusercontent.com/assets/13454532/16557422/431d5ccc-41e8-11e6-8cf0-37efa5f542b7.png)
