### ISSUE TITLE
Download pics by date?

### ISSUE THREAD

**Issue by Ruriko** [catgirlfighter/nekopaw#335]
Is there a way to downloads by date? like I only want to download pictures that were newly added in the last 10days

**Comment by catgirlfighter** [comment]
There is two possible ways:
- if source's engine supports keywords, you can use them to filter by a date;
- if source's engine provides that date as a field, you can get a full list, and then filter pictures from that list.

If resource doesn't provide functionality required, you can't do this.

**Comment by Ruriko** [comment]
If the source site is safebooru.org how do I filter it?

**Comment by catgirlfighter** [comment]
In safebooru best you can do is search normally and then filter by a field POSTED. gelbooru engine (used in safebooru) doesn't allow searching by a date.

**Comment by catgirlfighter** [comment]
To make things a bit more in order
