### ISSUE TITLE
Gelbooru.com webm videos being downloaded as static images.

### ISSUE THREAD

**Issue by Boxmanbr** [catgirlfighter/nekopaw#336]
As stated above.
Couldn't download any of those in webm format: http://gelbooru.com/index.php?page=post&s=list&tags=webm

**Comment by catgirlfighter** [comment]
should work now.

**Comment by Boxmanbr** [comment]
Yeah, I can download webm files now, but some of them are still being downloaded as images. (I'm using a proxy, not sure if the reason is because I get connection timeout when trying to download the webm).

**Comment by catgirlfighter** [comment]
Alas, that can be the case. Script uses the fastest way to get a picture (i.e. just trying to access it directly), and if it can't, it tries another extensions. I'll see what can be done to make it more strict.
