### ISSUE TITLE
e-shuushuu.net - don't work

### ISSUE THREAD

**Issue by asdfoo** [catgirlfighter/nekopaw#337]
Not loaded site e-shuushuu.net
Tried a proxy writes - e-shuushuu.net: @ thread.execute (): http://e-shuushuu.net/search/process/: Connect timed out.
Software version 2.1.0.148ἄ
What could be the problem?

**Comment by catgirlfighter** [comment]
Something's wrong with your proxy. Works fine for me.
![sample5](https://cloud.githubusercontent.com/assets/13454532/16556699/2d383c50-41e4-11e6-9250-f5bccb9db774.png)

**Comment by asdfoo** [comment]
proxy everything is fine just why it is that the site does not find
![2](https://cloud.githubusercontent.com/assets/20236469/16678910/7ab4caba-44ec-11e6-8349-391565e73234.png)
![3](https://cloud.githubusercontent.com/assets/20236469/16678916/82fc8f32-44ec-11e6-8c28-68c726bbdb5c.png)
![4](https://cloud.githubusercontent.com/assets/20236469/16678929/888b1e8c-44ec-11e6-9a5f-c414b19ef809.png)

**Comment by catgirlfighter** [comment]
Give me your resource presets and tags you use (make a screenshot of a list making page).

**Comment by catgirlfighter** [comment]
Also, are you sure that website is allowed in proxy's region? Probably it filtered out by resource itself or provider used by proxy.

**Comment by asdfoo** [comment]
![2](https://cloud.githubusercontent.com/assets/20236469/16706687/879ec316-45be-11e6-9f10-20765952e97f.png)
![3](https://cloud.githubusercontent.com/assets/20236469/16706691/8cbb0512-45be-11e6-93f2-7158ceb08468.png)
![4](https://cloud.githubusercontent.com/assets/20236469/16706692/9059819e-45be-11e6-9366-ab4be2b9fb99.png)
![5](https://cloud.githubusercontent.com/assets/20236469/16706693/936bcbbc-45be-11e6-8cb4-e2fc59a13bad.png)

I use a proxy Netherlands, some sites identifies some do not, and so with all the proxies of different countries.

**Comment by catgirlfighter** [comment]
I asked for a screenshot of list making page. I.e. when you making a list,
first page, right before you press "Finish". Not settings.

**Comment by catgirlfighter** [comment]
Og, I think I got what's wrong with your "proxy". Did you ever visit e-shuushuu.net? All your tegs should be with quotes to work (like "dress" "car" e.t.c.).

**Comment by asdfoo** [comment]
By tags work. And how to make that gave a list of the order as the images were published on a date? Or it works only with tags?

**Comment by catgirlfighter** [comment]
e-shuushuu.net doesn't give any other searching options except those nekopaw already provides. Search result is ordered by date by default (from new to old), but because grabber gets the list through multiple threads, order can be messed up. You can add  a "posted" column to the table and order by it, if you wish.
