### ISSUE TITLE
exhentai.org

### ISSUE THREAD

**Issue by LordYagami** [catgirlfighter/nekopaw#338]
How do I save downloaded images and their respective albums, (separate folders) and not all in the same folder as the default, sorry my English is not very good.

**Comment by catgirlfighter** [comment]
...\%album%\<therest>

**Comment by catgirlfighter** [comment]
ex.: $rootdir$\pics\<%album%>\

**Comment by LordYagami** [comment]
ok perfect, but as it is done so that the folder is automatically created with the images inside?

**Comment by catgirlfighter** [comment]
sure.
