### ISSUE TITLE
rule34.paheal.net empty list problem and possible solution

### ISSUE THREAD

**Issue by theadenter** [catgirlfighter/nekopaw#341]
In rule34.paheal.net.cfg there is:
`^section#id='image-list'{`
But should be:
`^section#id='imagelist'{`

After you correct it (in two places) - it will work and get the list of pictures.

**Comment by PapiRus01** [comment]
Solved а problem! Much appreciated.

**Comment by catgirlfighter** [comment]
Yep, they change names of tags from time to time, so fixes like this wind up.

**Comment by catgirlfighter** [comment]
Submitted to the source.
