### ISSUE TITLE
Rare issue on Hentai-foundry

### ISSUE THREAD

**Issue by HanatakeYurii** [catgirlfighter/nekopaw#344]
Hi,

I encountered a strange issue when trying to download "-April-" HF gallery.
I got 404 Not Found for every pic despite them existing.
I suspect "-" characters to mess around in the code.

Every other galleries are working well.

Am I right?

**Comment by catgirlfighter** [comment]
Yep, fixed it.

**Comment by HanatakeYurii** [comment]
Thanks a lot :D <3
