### ISSUE TITLE
hentai-foundry - 404 if author have dash in name

### ISSUE THREAD

**Issue by Pernat1y** [catgirlfighter/nekopaw#345]
If author have dash (-) in the name, then grabber gives 404 error while downloading images.

For example:
```
20:35:39 http://pictures.hentai-foundry.com/0/-KikeBrikex-/250820.%ext%: HTTP/1.1 404 Not Found
20:35:41 http://pictures.hentai-foundry.com/0/-KikeBrikex-/250185.%ext%: HTTP/1.1 404 Not Found
```

**Comment by catgirlfighter** [comment]
Found the thing. Usually they use first character of a nickname as a initial folder, and it's not an enlish letter, it just use 0. But in that case it's actually uses another character, and they replace "-" with "_" in a part of URL, that's why URL wasn't correct.
