### ISSUE TITLE
rule34hentai.net download stopped at 200 images.

### ISSUE THREAD

**Issue by Johnasan** [catgirlfighter/nekopaw#346]
How do I fix it? or how edit rule34hentai.net cfg file?

**Comment by catgirlfighter** [comment]
Didn't find a reason, why it happens?

**Comment by Johnasan** [comment]
I enter some tags or empty, it happened to me.

empty tags
![1](https://cloud.githubusercontent.com/assets/22637274/19116845/da6ffb90-8b51-11e6-950b-bb5032471829.jpg)

ex)Samus_Aran
![2](https://cloud.githubusercontent.com/assets/22637274/19116870/e9b357f0-8b51-11e6-8dc1-32e7e07bcce5.jpg)

my settings
![3](https://cloud.githubusercontent.com/assets/22637274/19116909/0a8e1c62-8b52-11e6-84cd-1bf6f314cc87.jpg)

rule34hentai.net.cfg
*preinstalled=0

[main]
$main.url='http://rule34hentai.net/';
$main.icon='rule34hentai.net.bmp';
$main.template = 'danbooru.tmpl';
$main.short = 'r34h';

$rplfrom = "'";

**Comment by catgirlfighter** [comment]
You wanted to edit a script for rule34hentai, but for it you should find a reason of a problem first. Try to list more then 200 pictures from site's GUI. Try to do the same from API.

**Comment by Johnasan** [comment]
yes, sorry for misunderstanding.
Nekopaw Grabber stopped when got list 200 at rule43hentai.net.
It automatically get till end of list if selected other resource site.

rule34.paheal.net
![4](https://cloud.githubusercontent.com/assets/22637274/19121497/b0251fc2-8b61-11e6-96ac-7685ea03330d.jpg)

xbooru.com
![5](https://cloud.githubusercontent.com/assets/22637274/19121510/bb1c8046-8b61-11e6-8121-99038876a47a.jpg)

**Comment by catgirlfighter** [comment]
You still misunderstanding me. Issue not in a grabber. Issue in resource itself.
Grabber works correctly, it's resource gives you only 200 pics.

**Comment by Johnasan** [comment]
ok, i got it.
Thanks for your reply.
