### ISSUE TITLE
FurAffinity not grabbing everything

### ISSUE THREAD

**Issue by JarieSuicune** [catgirlfighter/nekopaw#347]
I've been trying to get the gallery for:
http://www.furaffinity.net/user/jessicaelwood/
It says there should be 174 submissions, but each time I try to download the gallery, it gets only 88. I've been experiencing similar with other galleries there, with different numbers each.

**Comment by JarieSuicune** [comment]
Sorry, any idea if I may just have a setting funny?

**Comment by JarieSuicune** [comment]
Sorry, gonna bring this up again, is there a reason I can't bulk download any FurAffinity gallery completely, JessicaElwood's in particular?

**Comment by catgirlfighter** [comment]
I'll look into it today. Promise ( ͡° ͜ʖ ͡°)

**Comment by catgirlfighter** [comment]
Are you sure you're authorized? Is your NSFW switch disabled? Because I didn't have any issues.
![default](https://cloud.githubusercontent.com/assets/13454532/23035353/d5e3b1f0-f48f-11e6-81b0-ef42fcfc0b0a.png)

**Comment by JarieSuicune** [comment]
Hm, maybe because I wasn't logged in..?
Which... huh. I can't log in. Even changed my password just now to make certain. It brings up a captcha, but keeps failing.

**Comment by JarieSuicune** [comment]
I made sure all ratings are allowed in the program and on the site.

**Comment by JarieSuicune** [comment]
That would be in Resource Settings, right? I have everything for FurAffinity checked.

**Comment by catgirlfighter** [comment]
Yes, if you don't login, you can't download ALL.
Login sure works, I do it without issues. Unless you use unusual symbols in your password, and resource have some weird gimmick with converting them.

**Comment by catgirlfighter** [comment]
As a lost resort, you may also try to redownload the script for FA, just erase "resources\furaffinity.net.cfg=18" from settings.ini.

**Comment by JarieSuicune** [comment]
No, my login is a simple one, no symbols either. Hm. I'll
Hm. Ok. I'll try that after the current batch download finishes. (Which... is gonna be a while yet. So much to catch up on Pixiv!)
I'll let you know how it goes! Thanks!

I may just try a clean install too. It's not hard to restore settings to what I like.

**Comment by JarieSuicune** [comment]
Ok, so I tried a clean install to a different location... and I noticed a couple things.
Using the default settings, it found 128 hits.
Changing to have all options checked and Search by Username for the gallery, it went down to 88 again.

**Comment by catgirlfighter** [comment]
Main question is can you login now?

**Comment by JarieSuicune** [comment]
>_< It finally logged in and shows them all! Yay! (Apparently I had to remove the email extension from the login... huh.) Now to try on the old one! But at least I should be able to get things working one way or another!

**Comment by catgirlfighter** [comment]
Good to hear :)
