### ISSUE TITLE
Gelbooru не работает blacklist

### ISSUE THREAD

**Issue by Sandmonster** [catgirlfighter/nekopaw#348]
Не получается отсеять картинки по тегам. Прописал блэклист по тегам в настройках своего логина на сайте, кроме того в опциях программы указал те же самые теги, но в получаемом списке картинок есть те, которые там появляться не должны и убрать галки автоматически с этих картинок не получается.

**Comment by catgirlfighter** [comment]
Должно работать теперь.

**Comment by Sandmonster** [comment]
Скачал обновление, оно не заработало. У меня в блэклисте была одна строчка на несколько тегов типо ```tags:guro peeing vomit``` (на гельбуре теги разделяются пробелами, не знаю как на других). Я попробовал оставить только один тег, по нему уже удалось отфильтровать список. Я, в общем, не знаю, как правильно надо задавать теги, нигде вроде об этом не написано. Писать блэклист в виде 
```
tags:guro
tags:peeing
tags:vomit
``` 
не очень клево, но если так и задумано или надо использовать другие разделяющие символы, то стоит оставить где-то подсказку для таких нубов, как я.

**Comment by catgirlfighter** [comment]
да, тэги через запятую не укажешь, потому что тэги могут содержать запятые (почему нет?). Поэтому чтобы уж наверняка, надо указывать каждый тэг на своей строчке :)
