### ISSUE TITLE
Multi-page Pool Problem

### ISSUE THREAD

**Issue by ringtailedfox** [catgirlfighter/nekopaw#353]
I've discovered an odd issue with downloading pools with a large number of images from e621.net.... the program only grabs the first page (which is 24 or so images), and does not automatically jump to the next page to grab more... it's as if it treats the pool as limited to just 24 images.

e621's mult-page pool url format is https://e621.net/pool/show/12345?page=2 (as an example)

Attempting to append ?page=2 to the pool ID doesn't work, since the program automatically converts the symbols to alphanumeric HTTP code (like %3Fpage%3D2).

**Comment by zqjpymbk** [comment]
Development is dead. Don't bother.

**Comment by catgirlfighter** [comment]
You're not supposed to post pages through tags.
It was a deviation from original danbooru2 engine, it originally didn't have paging mechanics (or maybe didn't have in the past? idk).
Fixed it.
