### ISSUE TITLE
Лимит в 500 изображений.

### ISSUE THREAD

**Issue by truevectortrue** [catgirlfighter/nekopaw#357]
Хочу утащить по тэгу 1200+ картинок с chan.sankakucomplex.com.
Программа строит и загружает список только из 500 изображений.
В настройки и конфиг не смог.
Пожалуйста, подскажите что я делаю не так, будьте добры.
Спасибо за программу!

**Comment by catgirlfighter** [comment]
Ресурс показывает, что он содержит столько картинок по этому тегу, но не позволяет тебе качать так много. Иначе говоря, ресурс не позволяет тебе качать больше 500.
#358
