### ISSUE TITLE
500 images maximum

### ISSUE THREAD

**Issue by anyway01** [catgirlfighter/nekopaw#358]
Hey there, nekopaw, it's me again!

I don't have a real issue with the grabber, it's working just fine, but I have a question:

Why does the "TTL" have to be limited to 500 when there are way more images I'd like to download from chan.sankakucomplex.com? I don't know why this is necessary. Do I overlook something and can the limit be adjusted somewhere or do I really have to accept a limit of 500 images to download? If yes: Why? Why the limit?

Best greetings

anyway01

**Comment by catgirlfighter** [comment]
Hello there.
It doesn't matter, how much you want to download, it's about how much resource allows you to download. I.e. you should check if resource limiting you before making issues out of it :)

**Comment by anyway01** [comment]
I see. Thanks a lot for your fast reply.

Best greetings :)
