### ISSUE TITLE
limit for search results

### ISSUE THREAD

**Issue by hatabbich** [catgirlfighter/nekopaw#363]
hello, why in app list show less result with same tags from site page??? e.x 
tags:neko on site 50000 result
in nekopaw 37000 result (((

**Comment by catgirlfighter** [comment]
Probably filter settings. Site can _say_ it has 50k results, but not actually _show_ them. It can be seen by inconsistent amount of pictures on every page (it always different). If you'll provide me and example with actual resource, I'll check it.

**Comment by hatabbich** [comment]
ok, i was trying to load from sankaku this tags: "looking_back vagina naked barefoot" site results = 2700; graber2 result = 995;

**Comment by catgirlfighter** [comment]
Sigh. Did you COUNT them, or site just TOLD you there's 2700 results?
