### ISSUE TITLE
ATFbooru error

### ISSUE THREAD

**Issue by hatabbich** [catgirlfighter/nekopaw#365]
When i try login or search tags show this:

09:49:43 atfbooru.ninja: @thread.execute(): https://atfbooru.ninja/posts?utf8=✓&tags=loli&page=1: Socket Error # 11001
Host not found.
09:54:09 atfbooru.ninja error: https://atfbooru.ninja/session/new: Socket Error # 10054
Connection reset by peer.
09:54:09 atfbooru.ninja: login is failed
09:54:09 atfbooru.ninja: @thread.execute(): https://atfbooru.ninja/session/new: Socket Error # 10054
Connection reset by peer.

yesterday all was fine and download perfectly.

**Comment by HanatakeYurii** [comment]
Hello,

Got the same again and again:

13:54:32 atfbooru.ninja: @thread.execute(): https://atfbooru.ninja/posts?utf8=✓&tags=garabatoz&page=1: Socket Error # 10054
Connection reset by peer.

**Comment by RagaSonic** [comment]
Edit atfbooru.ninja.cfg with notepad and change $main.url = 'https://at*********inja/';
to http

**Comment by HanatakeYurii** [comment]
@RagaSonic It's working great, thanks!
Did someone pull requested this?

**Comment by catgirlfighter** [comment]
Added a fix. Sorry for making it a bit late (as usual :D).

**Comment by HanatakeYurii** [comment]
Thanks

**Comment by hatabbich** [comment]
yeaaaa!! ty you a best!!!
