### ISSUE TITLE
Please add tumblr

### ISSUE THREAD

**Issue by LTGM** [catgirlfighter/nekopaw#376]
Byd nyashei

**Comment by HanatakeYurii** [comment]
There are already good Tumblr crawler like [TumblThree](https://github.com/johanneszab/TumblThree) that does the job. Since there would be a lot of work and the author seems really busy, you should consider to use one of them instead of asking to implement it again.

**Comment by LTGM** [comment]
That's okay for me but how do I start it? Don't have any executable files after unpacking

**Comment by HanatakeYurii** [comment]
Well I assume you've downloaded the last release "TumblThree-v1.0.6.5.zip".
When unpacking there will be in the folder a file called "TumblThree.exe".
That's what you're looking for.

**Comment by LTGM** [comment]
I cannot find where to download the last release I see only "clone or download" option

**Comment by HanatakeYurii** [comment]
There you go: 
![tmp](https://user-images.githubusercontent.com/5856491/27739140-e26dfeee-5dad-11e7-9dc9-2cd412e9e03a.png)
[Releases](https://github.com/johanneszab/TumblThree/releases)

**Comment by LTGM** [comment]
My ad-block blocked it :D Thanks

**Comment by HanatakeYurii** [comment]
If it's okay for you, you can close this issue ^^

**Comment by LTGM** [comment]
close #376
