### ISSUE TITLE
Трансфер репозитория

### ISSUE THREAD

**Issue by HASTJI** [catgirlfighter/nekopaw#394]
Добрый день. Вижу что репо относительно заброшен, но в свое время очень хорошо программа спасала и помогала в задачах. Может есть возможность с вашей стороны передать репо под мое крыло, чтобы потихоньку восстановить работу программы и заново вдохнуть жизнь в рабочие процессы сиего гиганта граббинга контента? Попутно хочется много чего дописать и обновить, чтобы программа соответствовала современным запросам.

**Comment by catgirlfighter** [comment]
Можно ж просто сделать форк и делать дальше на его основе что угодно. Граббер распространяется под лицензией wtfpl.

**Comment by HASTJI** [comment]
Мне просто показалось странным если вот твой репо заморожен(образно говоря), а я буду под той же маркой продолжать работу над ПО. Ведь люди все равно будут искать по названию и натыкаться, в первую очередь, на твой репо, где видно что работы не ведутся и поэтому будут просто молча уходить)

ЗЫ - на счет лицензии. Я вообще нигде не нашел ее упоминания именно в репо, поэтому ведь, по умолчанию, все права принадлежат только тебе и никому более, поэтому, собственно, вопрос и возник. Нигде упоминания wtfpl в репо я найти не могу)

**Comment by catgirlfighter** [comment]
В этом случае лучше просто переименовать. Назови его graber 3 и начни как новый проект. Как ты можешь уже предположить, у меня никаких претензий нет. Это был "практический" проект, в нем много экспериментов и велосипедов, так что этот такой еще багаж.

**Comment by HASTJI** [comment]
Окей, понял. Благодарю за пояснения)
